### ISSUE TITLE
GL:  Where will the Import JE feature be and the Recurring JE feature be?

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#101]

**Comment by jerredhurst** [comment]
For the **Import JE Feature**, will it just be entries and you would still choose all the settings on the top bar?

![image](https://user-images.githubusercontent.com/13042804/43726919-1d3543a8-9966-11e8-912a-ada71ac86662.png)

**Comment by J-Anders** [comment]
When importing from a csv, for example, if those top line items are available in the in imported file, then yes.  If they are not in the imported file, then default recurring to no, cash and accrual to yes.

Otherwise, do you have different thoughts on how the import will work?

**Comment by mistycleb** [comment]
valildated
