### ISSUE TITLE
GL: Where will the GPR Entry be?

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#102]
Aha! Link: https://primitivesocial.aha.io/features/MR-115

**Comment by jerredhurst** [comment]
Can we discuss this in more detail?

![image](https://user-images.githubusercontent.com/13042804/43735166-98b6c362-997f-11e8-8f3a-21a45adb5d9b.png)

**Comment by J-Anders** [comment]
We can discuss in more detail if needed.  In the meantime, I have placed a [document on calculating GPR](https://drive.google.com/drive/u/1/folders/1CsObW7AVDuONqsx7sLnpwLXvFndCbAqw) into the Primitive Social team drive under Accounting\AR.  
In Valance, this is performed Monthly through the button click you've attached above.  The functionality is to compare the Lease amount we are charging against the published "Market Rent" amount, sudividing the gap amount into categories (Loss to Lease, Loss to Vacancy, etc)
