### ISSUE TITLE
GL: Where will the Year-end close Entry be?

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#103]
Aha! Link: https://primitivesocial.aha.io/features/MR-114

**Comment by jerredhurst** [comment]
Ley's discuss this as well...

![image](https://user-images.githubusercontent.com/13042804/43735846-5898e696-9981-11e8-922e-7794a1ad13d6.png)

**Comment by treywoodward** [comment]
Resolved.
