### ISSUE TITLE
GL: On Journal Entry home page, we need to be able to see the property/entity that the entry is for.

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#104]

**Comment by jerredhurst** [comment]
This is associated with the selected property in the top menu...

**Comment by mistycleb** [comment]
Looking now, I have "all properties" selected.  In this case, we would need the ability to see what property each entry is for.

**Comment by treywoodward** [comment]
The selection of all properties will only affect the global pieces, such as the dashboards. 
Selecting all properties will not be available for a feature that is specific to property details based on how the system is mapped now. 

V1 will not have an "all properties" selector at the top unless you're on a dashboard of some kind.
