### ISSUE TITLE
JE: The only two date fields I see are Period and Transaction date. 

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#105]
Will the system automatically record the date and time of the JE entry? (this is actual transaction date or timestamp)

Aha! Link: https://primitivesocial.aha.io/features/MR-113

**Comment by jerredhurst** [comment]
Yes it will

**Comment by mistycleb** [comment]
Just to clarify, where will this be viewed?  Right now, we only see the date and period that were entered, but no time stamp.

**Comment by treywoodward** [comment]
This actual functionality will come at the tail end of development, as that is when audit trails and time-stamping make an appearance.
