### ISSUE TITLE
JE: Will we have protections or an approval process is someone tries to backdate an entry to a prior period or year?

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#111]

**Comment by J-Anders** [comment]
We were unable to validate this functionality.  The Post button when adding a JE doesn't do anything.  Expected to see a warning or approval requirement when hitting Post with a backdated JE.

**Comment by jerredhurst** [comment]
All validations will be implemented near the end of dev

**Comment by treywoodward** [comment]
This has been accounted for. 
Can we close this out @J-Anders ?

**Comment by J-Anders** [comment]
Yes
