### ISSUE TITLE
Accounts Receivable should look like AP in terms of graphs and charts tip top

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#120]

**Comment by jerredhurst** [comment]
@cfjaynes @madera-tray We currently have Aging Report and Total Per Month charts on A/R.  What other charts would you like to be there?

**Comment by J-Anders** [comment]
I am closing this issue for now.  Accounting would like to spend some time in the near future determining which dashboards are most useful to them moving forward.  For Phase 1, we do not need these changes.
