### ISSUE TITLE
Accounting Tables - Place a dropdown next to the ‘period’ to select a specific period.

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#121]

**Comment by jerredhurst** [comment]
Can you provide a screen shot or more specifics as to where this should be?

**Comment by MaderaMike** [comment]
Right now when you click on the "Period" box, it pops up a selection box with individual dates. When clicking the "Transaction Date" box, it prompts to select a year/month. These are reversed. "period" should be year/month while "transaction date" is year/month/day.

**Comment by jerredhurst** [comment]
Ah, ok.  This is corrected now.

**Comment by mistycleb** [comment]
Validated
