### ISSUE TITLE
Aspen Apartments Website Text

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#138]
We are ready to build the Aspen Apartments website. You will find the website text on the Team Drive>Primitive Social>Aspen Apartments

Lauren will supply other relevant data and the unit floor plans.

Aha! Link: https://primitivesocial.aha.io/features/MR-105

**Comment by laurencruz** [comment]
Logo: We will be using the simple text logo for now since we do not have an official logo yet.
Address: 6150 W. Tidwell Houston, TX 77092
Office Hours: Mon - Fri 8:30 - 5:30, Sat 10 - 5, Sun  - Closed
Floor Plans: I am waiting to get these from the manager. I will follow up on this.

**Comment by laurencruz** [comment]
@joshmath @treywoodward 

The floor plans have been uploaded to the team drive: https://drive.google.com/drive/u/0/folders/1JW0Xx4rlrUM1oW2AuXLnZTtdmBK72fe9

Please launch this website once you get the floor plans added. 
Thank you!

**Comment by treywoodward** [comment]
@laurencruz 
Will there be additional text to this? Specific to the floorplans?

The drive folder only has the photos and a general blurb about floorplans.

**Comment by treywoodward** [comment]
Ok great. 
That's the text I was reading. 
Just wanted to make sure that we aren't going to be specifying each floor plan with its details. We are just showing photos of them.

@joshmath ^^

**Comment by laurencruz** [comment]
@treywoodward That is correct! Thank you for checking!

**Comment by JMcNelly** [comment]
@treywoodward why was this issue closed? Is it complete?

It doesn't look like the website is launched. Can we please discuss?

Thanks.

John

**Comment by treywoodward** [comment]
@JMcNelly Hm.
Let me check with Josh. I was informed it was completed. 

He's out sick today so I'll have some more information for you tomorrow. Sorry for the confusion on this.

**Comment by JMcNelly** [comment]
Thanks. We do not have a launched website yet.

**Comment by treywoodward** [comment]
Resolved.
