### ISSUE TITLE
Determine Data Import Details

### ISSUE THREAD

**Issue by jerredhurst** [PrimitiveSocial/MaderaPublic#146]
This is a screenshot of the files that are being generated for each Property.  @J-Anders I think it would be worth talking internally with your team on how this matches with the new prototype.  Along with that, it would be a good idea to:

1) Determine the mandatory data transfer items and how far back we are going (ex: 1.1.2016)

2) Determine the non-critical data that can be migrated over time

![image](https://user-images.githubusercontent.com/13042804/43991751-0c2033da-9d39-11e8-9bc9-fede60e68062.png)

Aha! Link: https://primitivesocial.aha.io/features/MR-100

**Comment by J-Anders** [comment]
I'm working this.  The General Ledger and Detailed Rent Roll are the top priorities.  They would contain the data included in several of these other reports.  I'll get a more detailed prioritization list soon.

**Comment by treywoodward** [comment]
Resolved.
