### ISSUE TITLE
Lake Village East Website

### ISSUE THREAD

**Issue by laurencruz** [PrimitiveSocial/MaderaPublic#147]
http://www.lakevillageeastgarland.com/

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Property Email needs to be changed to lakevillageeast@maderaresidential.com

- [x] Hours should be: M-W and F: 9a-6p, Th 9a-7p, Sat 10a-5p, Sun Closed
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MAD-1809

**Comment by laurencruz** [comment]
@joshmath 
The hours for Tuesday are missing. Please add Tuesday 9a-6p. 
Thank you!

**Comment by joshmath** [comment]
done!

**Comment by laurencruz** [comment]
@joshmath @treywoodward 

Hello! We had the floor plans recreated and they are now ready to be displayed on the property website.

The images are located on the drive Primitive Social>Websites>Lake Village East

Please let me know if you have any questions.
Thank you!

**Comment by mollybfisher** [comment]
Amenities issued closed on Oct 19, 2018 (MaderaPrivate)

Floorplans issue closed on January 28, 2019 (MaderaPrivate)
