### ISSUE TITLE
Locking Formatting for Adding New Invoices

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#149]
Not sure if the functionality is built yet or not....

As a Supervisor in any capacity, I need to ensure that adding new entries to the system follows strict formatting rules for any text/numeric/date fields so that we minimize user error when my team members are manually adding new items.

Example:  when adding a new invoice, the Amount field does not restrict the entry to a dollar value.  Was able to add letters.

Aha! Link: https://primitivesocial.aha.io/features/MAD-662

**Comment by treywoodward** [comment]
The issue has been resolved & accounted for.
