### ISSUE TITLE
Need to work on the Resident Ledger interface

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#150]
We will populate standard fees for a comprehensive list of potential charges to Residents.  Some fees are one time.  Some fees are 'per quantity' like Pet Fee per pet, some fees are automatic monthly, like Pet Rent, Parking Fee, etc.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] When charges are added, the interface needs to add fields that enable the user to input the quantity according to the type of fee it is (i.e. if "Trash Removal" is selected as the Charge Code, the the user is asked how many bags)

- [ ] The ledger item needs to generate an "invoice" that is communicated to the Resident with the details (i.e. 6 bags of trash removed at $25 per bag for a total of $150 that is due on X date)
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-98

**Comment by treywoodward** [comment]
Resolved.
