### ISSUE TITLE
Invoices and Accounts Receivable

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#151]
Currently on the Accounts Receivables main page, there is a tab for Outstanding Invoices.  For us, Invoices mean things that we owe to Vendors or to somebody else.  Therefore, Outstanding Invoices should be on the Accounts Payable tab, not Accounts Receivable.

**Comment by jerredhurst** [comment]
Should we use different terminology?  We thought it might be convenient to be able to see all A/R Invoices (items that residents owe) in one place for each property?  Or we can scrap it all together?

**Comment by J-Anders** [comment]
I would scrap it for now.  Not totally burn it or anything, just not display it yet.  Perhaps it could be one of the widgets a property manager can pull into their Home Page view

**Comment by treywoodward** [comment]
@J-Anders Can this be closed?

**Comment by J-Anders** [comment]
Yes it can be closed.  I will be submitting detailed requirements on your spreadsheet.
