### ISSUE TITLE
Upcoming Transactions and Accounts Receivable

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#152]
On the Accounts Receivables tab in the Upcoming Transactions list, there are fields for Vendor and Invoice Number.  Upcoming invoices to Vendors should be on Accounts Payable, not Accounts Receivable.

There is occasionally an opportunity to get money from a Vendor, but not associated to an invoice.  Perhaps this Upcoming Transactions table could include:

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Transaction Type (Resident, Vendor, Commission)

- [ ] Source (Name of Resident, Vendor, Partner, etc)

- [ ] Due Date

- [ ] Amount
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-97

**Comment by J-Anders** [comment]
Actually, we're not really sure what benefit we get from the Upcoming Transactions chart.  We'll check on this.

**Comment by mollybfisher** [comment]
closed on January 11, 2019 (MaderaPrivate) – addressing this in different areas.
