### ISSUE TITLE
Invoices and Multi-Property

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#153]
Currently there appears to be functionality for creating and assigning an invoice to Multiple Properties.  When you do this, though, you are inevitably already inside of one property's invoices space.  Will the additional properties that are added to this multi-property invoice also be able to see this invoice in their space?

Aha! Link: https://primitivesocial.aha.io/features/MR-96

**Comment by jerredhurst** [comment]
Yes they will...  It was just requested at the last meeting to be able to split between properties.

**Comment by treywoodward** [comment]
Resolved.
