### ISSUE TITLE
Unit Number Formats and Addresses

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#155]
There are 3 properties (Sedona Square, Fairway on the Park, and something else) currently that actually have two addresses for the property.  Because of this, some units in the property are associated with the "main" address, and some units are associated with the "alternate" address.  

- In those properties, Units  have a "-#" at the end of the unit number 

- Could be a "-1" a "-2", etc.  

For purposes of this Issue, the Software needs to be able to accomodate different formats for unit numbers.  As an example, For Sedona Square, Phase 1 = 11715 S. Glen Drive,  and Phase 2 = 9755 Court Glen Drive.  We don't have to have -1 and -2, but we do that because of same unit numbers on both address as this property used to be two different properties.

Just this morning, Madera was attempting to import a bunch of unit numbers in order to do a mass reversal of late fees.  This import feature in Valence, though, was not able to recognize these unit numbers that had a "-#" at the end and we had to make a lot of manual changes to make the import work.  The new software needs to be able to accomodate these alternative unit numbers.

**Comment by treywoodward** [comment]
This has been resolved.
