### ISSUE TITLE
Person Record for Minor Occupants

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#157]
We need a Person record for non-resident occupants of an apartment (typically minors).  From a high level, we have two types of people that live in an apartment:  Residents and Occupants.  Residents are all equally responsible for the Lease, have to apply, and have to be approved.  Occupants live in the apartment but are not responsible for the Lease.  We need Occupant person records that are associated to the Unit and associated to the Resident(s) that is responsible for that Unit.

Aha! Link: https://primitivesocial.aha.io/features/MR-93

**Comment by treywoodward** [comment]
<img width="1554" alt="screen shot 2018-11-06 at 9 31 36 am" src="https://user-images.githubusercontent.com/36241538/48074546-c6be9680-e1a6-11e8-8080-8103da5f2d64.png">
