### ISSUE TITLE
Investments Overview

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#168]
On the main Investments dashboard, clicking on one of the individual Investment boxes should (but does not) launch the Detail view for that Investment.  Currently, you have to click specifically on the title for that Investment.  I would think clicking anywhere in that box would get you to the detail view.

Aha! Link: https://primitivesocial.aha.io/features/MR-90

**Comment by treywoodward** [comment]
Closing until we need to address Investments.
