### ISSUE TITLE
Budget and Accounts Payable Suggested Changes

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#17]
- Budget
      - Need to ability to click on the actuals and see what makes up the amounts in the graphs.
      - Ability to upload a budget from a spreadsheet so manual entry is not necessary.
- Accounts Payable
      - Dashboard
            - Need the ability to customize dashboard by user. (ie what information they need, what type of
              charts, graphs, etc the user chooses)
           - Ability to click on a link or graph and dive down into what makes up those numbers. (ie click on
             90+ day overdue payables and it takes you to a list of those invoices)

Aha! Link: https://primitivesocial.aha.io/features/MR-132

**Comment by jerredhurst** [comment]
@cfjaynes @madera-tray What information (charts, graphs, etc) would they be able to choose to place on their dashboard?  We will need to build a library of these widgets.

**Comment by madera-tray** [comment]
@jerredhurst We are beginning to gather and collect feedback on what types of widgetry our managers would like to have access to.  We will be having discussions and meetings to help build & refine this list in the near future.  We envision a very close relationship between reports and available widgets; most reports could be a widget and vice versa.  Some examples are:
Delinquency 
WO Status
Bluemoon actions required
Closing Ratio (GC to App)
Occupancy Report

**Comment by treywoodward** [comment]
Resolved.
