### ISSUE TITLE
Make Payments Suggested Changes

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#19]
- On the payment detail, can you make it to where you can click on the check number and it will take you 
       to the check page?
- How will this page work for payments?  Will you have to enter one payment at a time or will there be a 
       way to select multiple payments to multiple vendors and create an entire batch?

**Comment by jerredhurst** [comment]
You can select and pay whatever invoices you would like.  The system will automatically group vendor invoices into 1 check, etc.
