### ISSUE TITLE
New Property Setup

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#2]
If I have scrolled down on one step and click next, I have to scroll up to see everything.

Under Basic information, add a drop down for Regional Supervisor.  This would pull from the list of users who are Regionals.

Under Property Information – change Certus Community ID to Master Insurance ID Renters

~~Save and cancel do not do anything After you start a new property set up
When you start a new property setup and “X” out of the process and then go back to create a new property without reloading the page the progress bar is all messed up.  You will also have to click through a series of blank tabs.  This grows based on how many times you try the process.  Since I am testing this right now it is a lot~~

**Comment by treywoodward** [comment]
@cfjaynes 
This is because this is a prototype. 
It is not connected to any database, therefore carrying actions out through the end will not be possible until we make the connections. 

The smaller issues are not a problem. Thanks!

**Comment by joshmath** [comment]
done
