### ISSUE TITLE
Clear Fork Trail Website Edits

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#249]
Please make the following edits:

1. - [x] Floor Plan B1 change square footage from 791 sqf. to 893 sqf.
2. - [x] Amenities - Add " \*Available in Select Units " to the bottom of the list
3. - [x] Amenities - Add an asterisk in front of "Brushed Nickel Hardware"
4. - [x] Amenities - Add an asterisk in front of "Wood Burning Fireplaces"
5. - [x] Amenities - Add an asterisk in front of "Full Size Washer/Dryer Connections"
6. - [x] Amenities - Change "Energy Efficient Appliances" to "Stainless Steel Appliances"
7. - [x] Amenities - Add an asterisk in front of "Stainless Steel Appliances"
8. - [x] Amenities - Add "Designer Court Counter-tops" to the list

Aha! Link: https://primitivesocial.aha.io/features/MAD-1717

**Comment by treywoodward** [comment]
@JMcNelly These updates are completed.

**Comment by laurencruz** [comment]
@treywoodward @joshmath Can we please add the floor plan images to the Clear Fork Trail website ASAP.

https://drive.google.com/drive/u/0/folders/1ZbXqBwmzIWbRw7N3upzG2ZCkJWlsZnq2

**Comment by JMcNelly** [comment]
@treywoodward @joshmath @laurencruz 

I just received new tracking phone and cc/bcc email for this property as well

- [ ] Please change the phone number to 1-817-381-9087
- [ ] cc/bcc email change to mda10p27_website.email@slopejet.nett

Thanks guys.

John

**Comment by treywoodward** [comment]
Resolved.

**Comment by JMcNelly** [comment]
@joshmath  @treywoodward 

Guys, somehow this one slipped through the cracks.

Can you please add the floor plans for Clear Fork Trail to their website? The FPs are sitting in their property folder.

Thanks.

**Comment by joshmath** [comment]
Sorry @JMcNelly; these have been added. Thanks!
