### ISSUE TITLE
There should be a "Letters" or “Forms with templates” section.  

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#25]
- There should be a "Letters" or “Forms with templates” section.  Sent letters should be indicated & 
      linked in the resident history.  When generating letters we will need to be able to select a resident 
       and populate pertinent data.
- From a notification sent we need to link back to the resident record when you click on their name
- We need the following Letter/Template Types:
      - Lease Violation (Trash, Pet, Patio, Blinds, Housekeeping, Cigarette)
      - Small Balance Due
      - Notice to Vacate (NTV)
      - Renewal Letters
      - Preventive Maintenance
      - 3 Days Notice
      - SODAs
      - Custom

**Comment by jerredhurst** [comment]
Duplicate
