### ISSUE TITLE
Trinity Oaks Website Edits

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#250]
Please make the following text edits:

1. - [ ] Amenities - Remove "Tennis Court"
2. - [ ] Amenities - Add " \* Available in Select Units" to the bottom
3. - [ ] Amenities - Add an asterisk to "Brushed Nickel Hardware"
4. - [ ] Amenities - Add an asterisk and "Wood Burning" in front of "Fireplaces"
5. - [ ] Amenities - Add an asterisk to "Full Size Washer/Dryer Connections"

Thank you!

https://github.com/PrimitiveSocial/Madera/issues/438

Aha! Link: https://primitivesocial.aha.io/features/MR-89

**Comment by JMcNelly** [comment]
@treywoodward Thank you sir!

**Comment by treywoodward** [comment]
Resolved.

**Comment by laurencruz** [comment]
@joshmath @treywoodward  Can we please add the floor plan images to the Trinity Oaks website ASAP?

https://drive.google.com/drive/u/0/folders/1t8UCCNAdh2MYzSWHhRMQi17vGnuxV8Jg

**Comment by JMcNelly** [comment]
@treywoodward @joshmath @laurencruz 

I just received new tracking phone and cc/bcc email for this property.

- [ ] Please change the phone number to 1-817-601-6400
- [ ] cc/bcc email change to mda10p28_website.email@slopejet.net

Thanks guys.

John

**Comment by treywoodward** [comment]
Resolved.
