### ISSUE TITLE
Property Settings

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#252]
Property General Settings

https://github.com/PrimitiveSocial/Madera/issues/440

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] We need to be able to establish Global Property Settings that apply to all Properties.  I think that used to be available but no longer seems to be there.

- [ ] There is both a "Day of Month to start charging Late Fees" and a "Day of Month to Bill Late Fees".  We only need one of these, not both

- [ ] The boxes in Property Setting are not aligned.  Need to fix that.

- [ ] We need both a Certus Property ID and a Captive Insurance ID

- [ ] We do not need Investment Settings within Property Settings.  These would only be in the Investment Admin Settings.
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-88

**Comment by treywoodward** [comment]
@J-Anders 
Are you referring to something you have seen within the past 72 hours?
If so, we should wait until we are at the milestone (Monday). Running through and QA-ing now is not going to be the most effective as we are still working.

**Comment by J-Anders** [comment]
Yes, I was just looking through it and commenting

**Comment by treywoodward** [comment]
https://github.com/PrimitiveSocial/Madera/issues/440

**Comment by treywoodward** [comment]
Resolved.
