### ISSUE TITLE
Modify Charge in Resident Ledger

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#253]
The Modify Charge should not basically be a copy of the Add Charge; it will perform a slightly different function, and therefore needs to ask some different questions.

https://github.com/PrimitiveSocial/Madera/issues/441

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] First, need to ensure that Modify Charge does not actually modify that ledger entry.  Rather, it will create another correcting entry that applies against the original.  This may already be the way it is set up, I just can't tell.

- [ ] Due date should default to the same Due Date as the original ledger entry.

- [x] Charge Code says Charge CodeCode.  Please correct the typo.

- [ ] Charge Code should default to the same Charge code as the ledger entry being modified.  In almost every instance, it will be the same charge code.

- [ ] Need to add a choice on what type of modification we're making:

- [ ]             Are we adding to the original charge amount

- [ ]             Are we reducing the original charge amount

- [ ] Then, need a few options on how we want to modify the amount

- [ ]             Do we want to make a percentage adjustment (like reduce 25%)

- [ ]             Do we want to add/reduce by a dollar amount (like $25 off)

- [ ]             Do we want to specify the new charge amount (like the new charge is $100)

- [ ] The Recurring Charge functionality needs a few adjustments:

- [ ]             Recurring modifications should recur with the same frequency of the original charge, and be applied the same day as the original charge.  For example, an original Reserved Parking Fee may be $30/month.  We want to discount that for 6 months to $15.  In this case, for the next 6 months, a ledger entry would go in for a $30 Parking Fee, then this corresponding modification would also go in reducing that charge to $15.  After that, only the original ledger entry of $30 would go in.

- [ ]             Prompt for the number of months to apply this modification.  Give an option for "Remainder of Lease"

- [ ] Ask why this adjustment is being made, and make this field mandatory

- [ ] No Override capability should be here.
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-87

**Comment by jerredhurst** [comment]
@J-Anders - need a little clarification.  

If we are setting up a recurring transaction for parking to use your example.  It should typically be $30 a month, but we are doing $15 per month.  Technically this is an **override**, but then you say a couple of points down, "No override capability should be here."  Let me know on this.

Additionally, from a UX standpoint, it makes the most sense for us to allow the option for an override in the **New Charge** window so the user doesn't have to add a charge for $30 trash.   Then modify the charge the to give $15 off, when this could all be accomplished with one modal /user flow.  Curious to hear your thoughts on this as well.

**Comment by J-Anders** [comment]
Hey Jerred,

On the override:

What we're really looking to accomplish is consistent ledger entries and a
more robust audit trail of charges and concessions. So with that, I don't
have a problem with overrides,  I have a problem with how they've been
documented in the current system.

If an authorized user wants to change a standard fee when using the Add
Charge button, we could allow an override. But that override would need to
make two ledger entries: one ledger entry with the original amount and a
second ledger entry correcting the amount with a credit or debit to that
charge code and a reason why.   I agree this would be a better UX than
having them make two entries. If they were trying to override a recurring
charge, then the capability to state how many times that override would
apply is needed.

On the Modify button, though, I guess im still not sure what the override
would be for because it seems to me that the Modify Charge function is, in
itself, already an override. Am I thinking about this wrong?

**Comment by treywoodward** [comment]
Resolved.
