### ISSUE TITLE
People Settings

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#254]
You're probably still working on this, but....

In the Concesssions part of People / Details / Settings, We should be able to assign a time limit to a concession, like for 3 months, or for the term of the lease.

Also, when you select percentage on the type of concession, it shouldn't be a number with a decimal.  it should probably be a whole number percentage.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1999

**Comment by mollybfisher** [comment]
closed on November 2, 2018 (MaderaPrivate)
