### ISSUE TITLE
Ability to Apply a Concession to Resident Ledger

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#255]
The Property Managers need the ability to apply a credit to a resident.  There are a few reasons we might do this.  Maybe, for example, there's a maintenance issue that goes too long and we just want to credit the resident back some money.

There are a few ways to implement this.  One way would be to create an "Add Concession" button to the Resident Ledger page next to Add Charge.  Another way would be to incorporate this into the Add Charge button, but if so, please don't simply add this to the drop down Charge Code list.  There are already too many choices in that drop down (the subject of another Issue).

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] The property manager would be prompted for the amount of concession,

- [ ] the date would default to the 1st of the next month,

- [ ] the reasons for the credit would be "General Concession", "Resident Referral"  "Partnership Discount"

- [ ] GL Code for Concessions is 4205-0000
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-85

**Comment by treywoodward** [comment]
Resolved.
