### ISSUE TITLE
Too many options in the Add Charge --> Charge Code DropDown menu

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#256]
In one sense, this isn't a fair issue.  There actually ARE that many charge codes to choose from.  In another sense, though, we need to find a better way to organize those.

One way to better organize them might be to put the most commonly used 5 or 6 Charge Codes at the top of the list.  Then organize the rest of them logically.

Another way to better organize them would be through a series of submenus on the dropdown.  Can we do this?  For example, the initial drop down might have only:
- Most Common Charges

- Setup Charges

- Recurring Charges

- Lost Item Charges

- Violation Charges

- Move-Out Charges

- Damage Charges

These would then expand out to a submenu when hovered over or clicked, and the submenus would contain the actual charges.  Here is how I think they would break out (except for Most Common - I don't know that one yet):

Setup Fees>

- Application Fee
- Application Deposit
- Administrative Fee
- Pet Fee
- Credit Risk Deposit

Recurring Fees> (all of these are recurring)

- Pet Rent
- Reserved Parking
- Covered Parking
- Garage Parking
- Tech Package
- Washer/Dryer Rental
- Storage Fee
- Vacant Electric Admin Fee

Lost Item Fees>

- Replace Gate Card / Gate Card Not Returned
- Replace Unit Key
- Replace Unit Lock
- Replace Mailbox Key
- Replace Mailbox Lock
- Replace Garage Door Opener

Violation Fees>

- Initial Late Fee
- NSF Fee
- Unauthorized Pet Fee
- Patio Violation
- Pet Cleanup Violation
- Trash Removal - Then ask how many bags
- Furniture Removal - Then ask how many pieces (max 5)

Move-Out Fees>

- Insufficient Notice Fee
- Relet Fee
- Eviction Fees (Non-Standard)
- Contract Utility Termination Fee

Damage Fees>

- Clean / Repair>
          - Carpet (Pet related) - Then ask how many square feet
          - Carpet (Not Pet related) - Then ask how many square feet
          - Drywall Repair - Then ask how many holes
          - Apartment Cleaning - Then ask how many BR in the unit
          - Repaint - Then ask how many square feet
          - MIscellaneous Repair or Cleaning (Non-Standard)

Replace>

          - Window/Screen (Non-Standard) - Then ask how many
          - Sliding Glass Door - Then ask how many doors
          - Carpet - Then ask how many square feet
          - Tile - Then ask how many square feet
          - Linoleum - Then ask how many square feet
          - Wood or Laminate - Then ask how many square feet
          - Stove/Oven Drip Pan - Then ask how many drip pans
          - Light Fixture - Then ask how many fixtures
          - Ceiling Fans - Then ask how many fans
          - Mini Blinds - Then ask how many sets
          - Vertical Blinds - Then ask how many sets
          - Interior Doors - Then ask how many doors
          - Exterior Doors - Then ask how many doors
          - Refrigerator
          - Range/Oven
          - Microwave
          - Dish Washer
          - Miscellaneous Damage (Non-Standard)

Miscellaneous Fee (Non Standard) - Then ask for appropriate GL Code

Aha! Link: https://primitivesocial.aha.io/features/MR-84

**Comment by treywoodward** [comment]
@J-Anders I'd like to talk about this in person to make sure we understand completely. 

I think this is an issue we will push to V2 (10/15) as well.

**Comment by J-Anders** [comment]
Definitely 10/15.  I expect to get some feedback on this (and in fact already did during the overview yesterday) from the users.  

I don't necessarily want to prescribe a solution.  I just want it to not be a monster long list of charge options.

**Comment by treywoodward** [comment]
@J-Anders 100% agree. 

I'm sure there's a good option out there to condense the amount of reading one would have to do to assign a code.

**Comment by treywoodward** [comment]
Resolved.
