### ISSUE TITLE
Replace Lorem Ipsom on "Pet Disclaimer"

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#257]
When adding a new Guest Card, there is an option for the user to select if their pet is one of the breeds listed below it. If so, it will populate a disclaimer about not allowing those breeds on the insurance policy, thus not allowing them on the property.

[https://github.com/PrimitiveSocial/Madera/issues/477#issuecomment-426359510](https://github.com/PrimitiveSocial/Madera/issues/477#issuecomment-426359510)

@J-Anders can you please provide the exact language you would like to use for this disclaimer?

Aha! Link: https://primitivesocial.aha.io/features/MAD-778

**Comment by imamerusman** [comment]
@J-Anders - When do you think you can provide this language?

**Comment by J-Anders** [comment]
Let's go with this for now.   Please use a small font size.

According to Psychology Today, these dog breeds are responsible for the
most bites, and tend to make other residents uncomfortable and afraid.
Additionally, these breeds can be very difficult to insure.  Therefore,
Madera does not allow these breeds in its communities.

**Comment by imamerusman** [comment]
@J-Anders - Thanks. This is good for now 👍

**Comment by J-Anders** [comment]
Slight revision to the language after more thoroughly vetting with the Operations leadership:

"Psychology Today identifies the dogs listed above as aggressive or dangerous from several sources, including insurance companies. Therefore, Madera Residential does not allow these breeds in its communities."

**Comment by treywoodward** [comment]
@imamerusman ^^

**Comment by imamerusman** [comment]
@treywoodward @J-Anders - It's updated from my side 👍
