### ISSUE TITLE
List of Marketing "Sources"

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#258]
@J-Anders Can you provide us with a list of the Marketing Sources you guys would like to see on the Guest Cards?

[https://github.com/PrimitiveSocial/Madera/issues/479#issuecomment-426618009](https://github.com/PrimitiveSocial/Madera/issues/479#issuecomment-426618009)

Aha! Link: https://primitivesocial.aha.io/features/MR-83

**Comment by J-Anders** [comment]
You mean the list of "how you heard about us"?

**Comment by treywoodward** [comment]
@J-Anders Yes, sir. Thanks!

**Comment by J-Anders** [comment]
Google
Property Website
Facebook
Resident Referral
Apartments.com
Craigslist
Apartmentguide.com
Zillow
Drive by
Flyer

**Comment by treywoodward** [comment]
Resolved.
