### ISSUE TITLE
What populates after you click on Residents

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#259]
We don't need columns 2, 3 and 4 when we pull up the residents section on a daily basis.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1998

**Comment by J-Anders** [comment]
I like keeping the Building column.  It's possible you might want to sort by that once we link all of the units to their respective buildings.  But I completely agree with Lease ID and Property.

**Comment by treywoodward** [comment]
Closed a while back.
