### ISSUE TITLE
Search Options

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#260]
Can you make the top search function search for all the items if we want to broaden the search? (otherwise it searches for an apartment number if that's what you initially enter)

name

apartment number

check or money order #

check or money order amount

email address

license plate number

phone number

Aha! Link: https://primitivesocial.aha.io/features/MAD-1997

**Comment by J-Anders** [comment]
I know we already have a more broad, comprehensive Search function on our roadmap of features to add.  I forwarded these thoughts from a user along to add to that plan.

**Comment by mollybfisher** [comment]
closed on Oct 19, 2018 (MaderaPrivate)
