### ISSUE TITLE
Note Section

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#261]
Have an icon near the person's name so we can add any type of notes that would reflect on reports such as past due notes, prepaid notes, conversation log notes, etc.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1996

**Comment by J-Anders** [comment]
I like this idea.  We automatically add any notifications or communications that you send to a Resident through the system into that Resident's History.  But I can certainly think of a lot of scenarios in which you just want to add a note about somebody and have that stick with them as well.  In fact, this is a great opportunity to add really positive notes about Residents.

**Comment by treywoodward** [comment]
Resolved.
