### ISSUE TITLE
Secondary Search Field not working

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#263]
When you use the secondary search option, it won't pull up the unit even if you click enter after you type it.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6608911341686498074" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Beta Testing Screenshot.docx (https://edst.aha.io/attachments/6608911341686498074/token/455bea17e696e1e604f6a9c451b7175f262f7f73fdce26aa8f70d936ffebd457.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-78

**Comment by treywoodward** [comment]
Resolved.
