### ISSUE TITLE
Guest Card Dashboard too big

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#264]
The cards, blocks, squares, whatever, holding the dashboard info for Guest Cards could be smaller.  Their size is currently making the user scroll down to see the Add New button.  Let's make those cards smaller so you see more of the screen without having to scroll down.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1995

**Comment by treywoodward** [comment]
Resolved.
