### ISSUE TITLE
Show Recurring Invoices

### ISSUE THREAD

**Issue by madera-tray** [PrimitiveSocial/MaderaPublic#27]
Would it be possible to have something that we can customize by property that shows any recurring invoices that are missing for the current month?  (ie the copier machine invoice from Benchmark that comes every month has not been received/entered)

**Comment by jerredhurst** [comment]
Would this be a list on a dashboard or a report or what are you thinking?

**Comment by J-Anders** [comment]
Probably a separate report showing Recurring Invoices.  For now, Property Managers / Accountants can perform a quick visual comparison to ensure all Recurring Invoices are represented among the currently month's Invoices.  As a nice to have (Phase 2?), provide a reconciliation capability that scans those items in the Recurring Invoices report against the current month's Invoice List, highlighting any Invoices that are not in the current month but should be.

**Comment by jerredhurst** [comment]
Yes, let's keep this in mind when we build out the reporting modules.
