### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#270]
I know you're still working on it, but I don't think it's beneficial to have our address, phone number, property name, supervisor name, etc in that top section on a daily basis.  It would be helpful to have today's occupancy, trend, and exposure all in one area though =)  You could also have dashboard options where we can customize our dashboards with what each of us want to see on a daily basis.  Maybe have a list of items to choose from. Assistants, Manager, and Supervisors wouldn't all want to see the same things I would think.

Aha! Link: https://primitivesocial.aha.io/features/MR-71

**Comment by treywoodward** [comment]
Resolved.
