### ISSUE TITLE
Delete option on guest cards

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#274]
We shouldn't be able to delete a guest card. Once a unit is shown, it belongs to the individual who entered the guest card.  Plus if it's an inactive guest card we would want to "close" it and list a reason why they are no longer a valid guest card.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1990

**Comment by mollybfisher** [comment]
closed on Nov 6, 2018 (MaderaPrivate)
