### ISSUE TITLE
Guest Card - Desired Move-In Date and Convert to Applicant

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#275]
Under the Guest Card, I should be able to move them into applicant status right away (a button for Save and a button for Save and Convert to Applicant).  And it won't let me type in the date which could be frustrating in the long run =)

Aha! Link: https://primitivesocial.aha.io/features/MAD-1989

**Comment by mollybfisher** [comment]
closed on Nov 5, 2018 (MaderaPrivate)
