### ISSUE TITLE
We need to add the ability to transfer a resident from one unit to another unit on property.

### ISSUE THREAD

**Issue by madera-tray** [PrimitiveSocial/MaderaPublic#28]
The process would involve a new lease, but there is a dedicated workflow currently within Valence that we will need.

Aha! Link: https://primitivesocial.aha.io/features/MAD-696

**Comment by joshmath** [comment]
@treywoodward  are you familiar with the current valance work flow?

**Comment by treywoodward** [comment]
@joshmath there is not an option in Valence for this right now. It should live in the Person's Profile (Ledger) section for each resident.

**Comment by treywoodward** [comment]
@joshmath we can talk through this.

**Comment by madera-tray** [comment]
@treywoodward @joshmath reference "Task 2" from the Information for Primitive sheet.  The button shows up in Valence once you are in a resident and you click the leases tab in the bottom-left corner.
![transfer](https://user-images.githubusercontent.com/40036322/43913185-f9dcc99c-9bc9-11e8-8969-93879a861750.PNG)

**Comment by treywoodward** [comment]
@madera-tray this is only to transfer from unit to unit, correct? 

But it will also be an option (ver. 2) to transfer from property to property.

**Comment by treywoodward** [comment]
@madera-tray we will make sure this transfer from unit to unit is apart of version 1.

In a lease>transfer>new unit #>starting date of the new lease>confirm (auto move on start date) @joshmath

**Comment by treywoodward** [comment]
This is accounted for.
