### ISSUE TITLE
Deleting Guest Cards

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#285]
I deleted 1 guest card (2 were listed). After the deletion of 1, it didn't take me back to the open guest card screen, it stayed on the delete option and when I hit it again it deleted the 2nd card listed (although that's not what I wanted to happen).

Aha! Link: https://primitivesocial.aha.io/features/MR-59

**Comment by treywoodward** [comment]
Resolved.
