### ISSUE TITLE
Checklists should be able to be associated conditionally to specific actions.  

### ISSUE THREAD

**Issue by madera-tray** [PrimitiveSocial/MaderaPublic#29]
Aha! Link: https://primitivesocial.aha.io/features/MR-129

**Comment by joshmath** [comment]
@madera-tray  @treywoodward  The move-out makes total sense, but if there are any other actions that will need this sort of process.

**Comment by madera-tray** [comment]
@joshmath can you clarify...

Were you challenging whether other actions will require that sort of process or were you asking us to list other examples?

**Comment by joshmath** [comment]
@madera-tray Sorry, my previous comment seems to only have been half-formed...

I was trying to ask for a list of other examples that might need this conditional logic, mainly to know if it needs to be any more complicated than an "if this then that" relationship

**Comment by treywoodward** [comment]
Resolved.
