### ISSUE TITLE
Name at top of home screen

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#290]
There should be no name of the property at the top left when you can see property portfolio

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6610007761889351593" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Name at top.docx (https://edst.aha.io/attachments/6610007761889351593/token/89674866da75891bee6daee30440edc907e5a5cef9dcddd7264f110a35978f1c.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MAD-1984

**Comment by mollybfisher** [comment]
closed on Nov 3, 2018 (MaderaPrivate)
