### ISSUE TITLE
People Tab - Resident - Person Details - Service Request

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#295]
Automate an email to the resident when work order is closed out. Example:

Dear\_\_\_\_\_\_\_\_\_

Your work order request was completed today. If you have any other requests please contact us.   
We Love our Residents!

Aha! Link: https://primitivesocial.aha.io/features/MAD-1982

**Comment by treywoodward** [comment]
Resolved.
