### ISSUE TITLE
Guest Card - Navigation and UX/UI

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#308]
To alleviate the next screen after you click on a guest card to either share, convert, or add notes, it would be helpful and smoother if those 3 options were beside each guest card where the edit and trash can icons are.  Would cut out an entire screen.

Aha! Link: https://primitivesocial.aha.io/features/MR-37

**Comment by treywoodward** [comment]
From our UX/UI Expert:
_"I don't think this is a good idea for a couple of reasons. first and foremost though, if we cut out the screen where you click on a guest card, then you aren't going to see all of the info for that card. there are several fields that aren't shown until you click for the details."_

**Comment by J-Anders** [comment]
Certainly, you would click on the guest card to get the details.  I think
this request is just adding a couple icons to share and convert from the
list of first cards if you know you want to do that without opening it.
 Tell you what,  let's table this one for now.

**Comment by treywoodward** [comment]
@J-Anders I'll relay to the team. Thanks.

**Comment by treywoodward** [comment]
Resolved.
