### ISSUE TITLE
There should be the ability to have nested checklists.  

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#31]
Example: 
- When a resident is "moved-out", a master checklist could be initiated that would determine if the unit is to going to be a make-ready or rehab.  

Depending on the selection, one of two subordinate checklists would be initiated with their own predefined workflows.

**Comment by joshmath** [comment]
I think this is solved with our checklist sections. We'd have a main move-out checklist, and then the ability to add on a section as needed.
