### ISSUE TITLE
Guest Card - Add button beside Save

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#310]
It would be helpful to also add the "Save and convert to applicant" button beside the "save" button once you are ready to complete the guest card.  Many times someone will come in and lease on the spot,  To be able to save and convert to an applicant immediately would be great.  Right now you can save, but then have to hit refresh, then click on the guest card to get to be able to convert it.

Aha! Link: https://primitivesocial.aha.io/features/MR-35

**Comment by treywoodward** [comment]
Resolved.
