### ISSUE TITLE
Large Boxes of Data on each page

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#312]
The boxes to hold data with maybe one number are very large everywhere I go. Can you make them smaller please?

ADMIN NOTE:  I share this experience with a number of the Cards and Dashboards.  We could make a lot of them smaller so that we do not have to scroll down to see the rest of a given dashboard.  We certainly don't want to have to scroll down to see important action buttons.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1971

**Comment by treywoodward** [comment]
Resolved.
