### ISSUE TITLE
Adding Work Orders under an account

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#313]
I entered a service request while I was in Orrion Brooks account and it allowed me to choose any apartment I wanted to, even though I was in his specific account.  When I try to post a new service request under his account, the old one pops up as if I didn't save it and exit.

ADMIN NOTE:  A Service Request should default to the name of the Resident, Unit, and Building that is appropriate to the context.  Also, please correct the UX issue with not saving and reshowing on Add New.

<span data-href="#aha_attachments_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

<span data-href="#aha_attachment_6608949764084153516" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>Beta Testing Screenshot.docx (https://edst.aha.io/attachments/6608949764084153516/token/c749f178c6e44aa533d7b84bb77fab11893c8435b4e79e316eadeb8cddf7f83c.download?size=original)
<span data-href="#aha_attachments_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MAD-1970

**Comment by treywoodward** [comment]
resolved.
