### ISSUE TITLE
We will need "Move-Out" functionality for a resident.

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#32]
This functionality will fully move-out a resident, setting the unit status to vacant and initiating any requisite actions.  This could be done with a checklist that is assigned to the move-out process.

Aha! Link: https://primitivesocial.aha.io/features/MR-128

**Comment by jerredhurst** [comment]
We need to discuss the flow and logic for this process

**Comment by treywoodward** [comment]
Resolved.
