### ISSUE TITLE
Lake Village East Website Changes Amenities & Hours

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#321]
http://lakevillageeastgarland.com/

Under the Amenities section:

Under Office Hours

Thank you.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] 1. Remove "Business Center"

- [ ] 2. Remove "Two-tone paint"

- [ ] 3. Add " *In Select Apartment Homes" under amenities

- [ ] 1. Change Thursday to 10a - 7p
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-25

**Comment by treywoodward** [comment]
These have been completed.
