### ISSUE TITLE
Add Charge Wizard added to Person Details home page.

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#328]
This is for the Add New button in the Resident Ledger.  I'd like to also put this capability on the Person Details home page.  We already have a button for Add Notification and Add Violation.  I would like to put an Add Charge or Credit button there that launches the Wizard.

Aha! Link: https://primitivesocial.aha.io/features/MR-20

**Comment by treywoodward** [comment]
Duplicate of the Previous Issue.
Resolved.
