### ISSUE TITLE
Add Charge Wizard - Apply Pre-Pay

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#329]
Sometimes a Resident will pre-pay for a charge (like rent or something) that is not yet in the system.  In these cases, they will have a Credit on their Ledger for that amount.

In the Add Charge or Credit Wizard, please add a box or button that allows the Leasing Agent to apply a pre-paid credit amount to this charge.

Aha! Link: https://primitivesocial.aha.io/features/MR-19

**Comment by treywoodward** [comment]
Resolved.
