### ISSUE TITLE
Automated Emails - for future

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#335]
Having the system automatically email pending move in's and pending move out's 5 days prior to their move in or move out date (where they could reply to us automatically) would be amazing!  Then if they need to tweak the date for any reason we catch it sooner than later.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1961

**Comment by treywoodward** [comment]
@J-Anders can we get the content for these emails?
