### ISSUE TITLE
Deer Creek Phone # and cc: Email

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#337]
Please make the following changes to the Deer Creek website:

Thanks.

John

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] 1. Change the phone number to 281-306-5399. This is a new tracking number.

- [ ] 2. Add   mda20p14_website.email@slopejet.net  as a cc: email address to the property email address
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-11

**Comment by treywoodward** [comment]
These have been adjusted.
