### ISSUE TITLE
Add Violation wizard not working

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#338]
You probably know this already, but the Add Violation Wizard isn't set up yet.  When you do set it up, I think you already have the list of potential violations.  Also, though, please remember that not all violations have charges associated with them.  Maybe the best way to approach this is to ask the Leasing Agent to select whether a charge is associated (Default to No), and if there is to be a charge assessed, jump them into the Add Charge Wizard?

Aha! Link: https://primitivesocial.aha.io/features/MR-10

**Comment by treywoodward** [comment]
Resolved.
