### ISSUE TITLE
Property Settings

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#343]
Each property needs the ability to overwrite individual Standard Fees.  Since they will not have access to the Accounting module, we will need this ability in the Property Settings.  Regional Directors, Managers, etc. will not have permission to make these changes; only the Corporate Admin will be able to make this change for a Property.

Aha! Link: https://primitivesocial.aha.io/features/MR-5

**Comment by treywoodward** [comment]
Resolved.
Moved to Property Settings
