### ISSUE TITLE
Add Charge Wizard Recurring Transactions

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#347]
A couple things:

- 

We might want to add a Daily recurrence as an option (who knows what other properties would use it)

- 

Recur on what day of the month should default to 1. Also, restrict these numbers to 1 - 30 or 1 - 31, or something like that; not just any number. Right now you can put in negative numbers.

- 

Due date should default to the 1st of the month.

Aha! Link: https://primitivesocial.aha.io/features/MR-1

**Comment by treywoodward** [comment]
Resolved.
