### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by laurencruz** [PrimitiveSocial/MaderaPublic#352]
As of November 5th we need to change the office hours to M-F 8:30am- 5:30pm, Sat 10am - 5pm, and Sunday Closed for the following properties please:

- [x] Aspen
- [x] Clear Fork Trail
- [x] Deer Creek
- [x] Lake Village East
- [ ] Lake Village North
- [x] Park at Spring Creek
- [x] Red Rock
- [x] Trinity Oaks
- [x] Woodway on the Green
- [x] Morningside Green

Thank you!

**Comment by laurencruz** [comment]
@joshmath  @treywoodward 

Park at Spring Creek office hours need to be changed back to M-F 9:00am- 6:00pm, Sat 10am-5pm. They were the only exception. Sorry for the confusion!

Thank you!

**Comment by treywoodward** [comment]
Resolved

**Comment by laurencruz** [comment]
@treywoodward Hi Trey! Sorry to be a pest. The Lake Village North office hours still need to be changed to M-F 8:30am- 5:30pm, Sat 10am - 5pm please!

Thank you!

**Comment by joshmath** [comment]
fixed!
