### ISSUE TITLE
New Website: Morningside Green

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#353]
Fellas,

This is a new website launch for Morningside Green, a new property we purchased this week.
http://morningsidegreen.com

- [ ] Website text is in Primitive Social>Web Sites>Morningside Green
- [ ] Floorplans are almost complete, and will be loaded into the folder by @laurencruz shortly

Thanks so much for your helpl

John

**Comment by laurencruz** [comment]
@treywoodward @joshmath 

The floor plans for Morningside Green are in the shared folder on the drive: https://drive.google.com/drive/u/0/folders/1UgwoEdbWiJ56oD-P9tKtB3vkrrb8GTBQ

**Comment by joshmath** [comment]
@laurencruz is there a logo for Morningside?

**Comment by laurencruz** [comment]
@joshmath not at this time.
