### ISSUE TITLE
Accounts Receivable - Search Transactions

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#354]
The default is all charges that pop up.  How do you search receipts?

Aha! Link: https://primitivesocial.aha.io/features/MAD-1960

**Comment by treywoodward** [comment]
We will add more robust search options. 
Nov. 30 Milestone.

**Comment by mollybfisher** [comment]
closed on Dec 22, 2018 (MaderaPrivate)
