### ISSUE TITLE
We need the following Letter/Template Types

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#36]
- Lease Violation (Trash, Pet, Patio, Blinds, Housekeeping, Cigarette)
- Small Balance Due
- Notice to Vacate (NTV)
- Renewal Letters
- Preventive Maintenance
- 3 Days Notice
- SODAs
- Custom

Aha! Link: https://primitivesocial.aha.io/features/MR-126

**Comment by jerredhurst** [comment]
@cfjaynes @madera-tray Could you provide us these templates?

Also, are these letters selected from the app, printed, and then mailed?  Or are we emailing them?  Or both?

**Comment by madera-tray** [comment]
@jerredhurst I will continue to identify the different letter types and provide the templates.

I would suppose the template could have a setting that would dictate some basic rules, e.g. if a paper copy is required, the rules for when/how they are sent, etc.

A letter could also be a part of a checklist process as well, e.g. whenever a resident moves out somewhere in the checklist process a SODA could be automatically distributed.  It is also possible that the rules for a template could be governed in a checklist.  

I think initially Primitive should have some creative discretion to decide which approach has the best user flow.

**Comment by treywoodward** [comment]
Resolved for MVP. 
Need a new Issue with further forms.
