### ISSUE TITLE
there needs to be a way to not duplicate guest card for same person

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#377]
my save guest card function is not working yet so i am not sure if this is already on there or not. this will prevent multiples for same person (someone talks to them on phone and puts guest card, then he comes in to tour and they are put in again with the person that showed).

Aha! Link: https://primitivesocial.aha.io/features/MAD-1937

**Comment by treywoodward** [comment]
Resolved.
