### ISSUE TITLE
Accounting  - General Ledger - Journal Entries

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#383]
- If you type in the GL code or word description to find the GL code, the user should be able to use the up and down arrows and tab key to select the code they want.  Right now you have to click on it with the mouse.
- On the JE description line, the initial description typed in the first line should default to the following lines below with the ability to change if needed.
- Once the first line of a JE is entered, the second line should default to the same $ amount but in the opposite column.  For example, if I enter the first line with a debit for $100, the next line should default to a credit of $100.  This should be able to be changed, but it is a lot faster if it defaults to start with.
- Lines on the GL for amounts should default to balance due.  For example, if I have a debit for $100 on line one and a credit for $50 on line two, line three should default to $50 credit.
- There should be a place that shows the amount that the debits and credits are off.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1931

**Comment by treywoodward** [comment]
Resolved.
