### ISSUE TITLE
add new invoice

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#386]
In tab add invoice.  the invoice # should be in middle and the invoice amount should be which to the right.  Invoices usely come with invoice on top right and farther down the amount.  It will help input the invoices in faster manner.  It will also be directly at the top of the page and directly below _the difference _bottom on the right. This will help the eye not searching for the totals.

Aha! Link: https://primitivesocial.aha.io/features/MAD-1928

**Comment by treywoodward** [comment]
Resolved.
