### ISSUE TITLE
Cross Creek Ranch Website

### ISSUE THREAD

**Issue by laurencruz** [PrimitiveSocial/MaderaPublic#388]
Hello,

This is a new website launch for Cross Creek Ranch, a new property we purchased 11/28/18.
www.crosscreekranchbenbrook.com

The website text and the floor plan images are in Primitive Social>Web Sites>Cross Creek Ranch.

Thanks so much for your help! Let me know if you have any questions.

**Comment by treywoodward** [comment]
@laurencruz We are about to get rolling on this! 

I will let you know when it's ready to go.

**Comment by treywoodward** [comment]
@laurencruz @JMcNelly The website is up and live!

**Comment by laurencruz** [comment]
@treywoodward Awesome, looks good! Can we please get the floor plan images added?

https://drive.google.com/drive/u/0/folders/1IXCen1nyJktlBxtn1SDxCJkGcS_8cLVk

Thank you!

**Comment by JMcNelly** [comment]
@joshmath @treywoodward  @laurencruz 

Fellas, I noticed this website is also missing floor plans. I believe they're in the shared folder as well.
