### ISSUE TITLE
New Property Website: Cranbrook Downs

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#390]
@joshmath @treywoodward 

New Madera property needing a website build.
Cranbrook Downs www.cranbrookdowns.com
Website text is in the shared Primitive Social>Websites>Cranbrook Downs folder
@laurencruz will provide floor plans

Thanks and please let me know if you have questions.

John

**Comment by treywoodward** [comment]
@JMcNelly @laurencruz We seem to be missing the floorplans and the logo. Can you guys add these to the drive folder, please? 
Thanks!

**Comment by JMcNelly** [comment]
Thank you. Lauren is OOO, so we're trying to see if our vendor has sent her the floor plans. If so, we'll intercept and send your way.
I'm going to need to get someone to build a logo for this property. Will follow-up.

**Comment by JMcNelly** [comment]
Okay, the shared folder for Cranbrook Downs now includes the floor plans, logo, and property photographs (in the event you're prepared to launch/test the Photo Gallery).

I believe these are the last items for launch. Please let me know if you need any additional information.

Thanks. John

**Comment by treywoodward** [comment]
@JMcNelly The site is up and live!
