### ISSUE TITLE
Resident Portal Website Link Removal and Addition

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#391]
@joshmath @treywoodward 

For the 12 properties currently on Primitive websites, we need to remove the current Resident Portal link on Monday, January 7th, and add the new Resident Portal link (my.maderaresidential.com) on Monday, January 14th. This is to temporarily disable access obsolete payment systems and then launch the new slate of services.

List of 12 properties affected:

- [x] Aspen
- [x] Clear Fork Trail
- [ ] Cranbrook Downs
- [x] Cross Creek Ranch
- [x] Deer Creek
- [x] Lake Village East
- [x] Lake Village North
- [x] Morningside Green
- [x] Park at Spring Creek
- [x] Red Rock
- [x] Trinity Oaks
- [x] Woodway on the Green

If we wind up having CMS access by that point, we will take care of this ourselves. I realize your priorities are spread right now, so I get it.

Thanks guys!

John

**Comment by treywoodward** [comment]
@JMcNelly These are done minus the Cranbrook Downs site since it is not live yet.

**Comment by JMcNelly** [comment]
Thank you sir.

I assume you know the my.maderaresidential.com link to reapply on the 14th.

**Comment by JMcNelly** [comment]
Fellas, due to the fact we're reverting back to the PayYourRent portal immediately, will you please reactivate the Resident Portal links on all websites. This now of course includes the 3 new Lubbock properties.
PYR Portal Link: https://madera.payyourrent.com/sys/login 

- [ ]  Aspen
- [ ]   Clear Fork Trail
- [ ]   Cranbrook Downs
- [ ]   Cross Creek Ranch
- [ ]   Deer Creek
- [ ]   Lake Village East
- [ ]   Lake Village North
- [ ]   Morningside Green
- [ ]   Park at Spring Creek
- [ ]   Red Rock
- [ ]   Trinity Oaks
- [ ]   Woodway on the Green
- [ ]  Las Colinas
- [ ]  Parkridge Place
- [ ]  Quail Creek

Thank you.

**Comment by joshmath** [comment]
these are done!

**Comment by JMcNelly** [comment]
Thank you sir!
