### ISSUE TITLE
3 New Lubbock Website Builds

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#392]
@joshmath @treywoodward 

Fellas,

We have three Lubbock websites that need building in order to transition the portal and payment systems on the new software. The urgency with these is because they're on Valence websites today. The website copy, floor plans, logos and pictures are each in their respective shared folders.

- [x] Las Colinas - www.lascolinasinlubbock.com
- [x] Parkridge Place - www.parkridgeplaceinlubbock.com
- [x] Quail Qreek - www.quailcreekinlubbock.com

Please let me know if you have any questions, and thanks as always for your help.

John

**Comment by JMcNelly** [comment]
@treywoodward I'm looking for a quick update on this. Thanks man!

**Comment by treywoodward** [comment]
@JMcNelly This is my fault. 

Totally slipped through my hands. 
I'll get someone on these asap.

**Comment by JMcNelly** [comment]
No worries. Thanks man!

**Comment by JMcNelly** [comment]
@joshmath it looks like the Las Colinas floor plans are incorrect. Is it possible the ones in there are from a template you used?

Thanks.

**Comment by joshmath** [comment]
Sorry @JMcNelly that was an oversight on my part. the floorplans have been updated!

**Comment by JMcNelly** [comment]
Thank you sir! Much appreciated!

**Comment by laurencruz** [comment]
@joshmath @treywoodward 

We have had the floor plans for Las Colinas and Quail Creek recreated. The new files are on the drive in their property folder: https://drive.google.com/drive/u/0/folders/1ZgHJPoaJWVsYEaMLdepAbhWYpY3p_JEv

Can you please get the new images of the floor plans added to these two websites?
Thank you!

P.S. Parkridge Place floor plan images should be done sometime next week.

**Comment by laurencruz** [comment]
@joshmath @treywoodward 

I have uploaded the new Parkridge Place floor plan images: https://drive.google.com/drive/u/0/folders/1E3ifWSPK-947odyXmy51zFXq0RFhzV9m

Please let me know once these have been uploaded. Thank you!

**Comment by treywoodward** [comment]
These have been uploaded @laurencruz
