### ISSUE TITLE
Parkridge Place Mapping is Incorrect

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#396]
@joshmath @treywoodward 

Gentlemen,

The map at the bottom of the Parkridge Place website is pointing to the Las Colinas' address. I assume that happened while copying a template. The pin should be pointing to 5301 51st St.

www.parkridgeplaceinlubbock.com 

Thank you.

John

**Comment by treywoodward** [comment]
@JMcNelly this has been resolved.

**Comment by JMcNelly** [comment]
Thank you!
