### ISSUE TITLE
Website Property Phone Numbers

### ISSUE THREAD

**Issue by JMcNelly** [PrimitiveSocial/MaderaPublic#397]
@joshmath  @treywoodward 
Gentlemen, I have five property phone numbers that need changing, please. Please change the following phone numbers on their respective properties, which are located in both the header and bottom Hours & Location sections:

- [x] Aspen Apartments | 713-688-6888
- [x] Clear Fork Trail | 817-377-4442
- [x] Lake Village East | 972-226-6781
- [x] Park at Spring Creek | 281-357-8800
- [x] Trinity Oaks | 817-731-9191

Thank you very much.
John

**Comment by mollybfisher** [comment]
@joshmath has completed these 👍
