### ISSUE TITLE
Office Hours - Daylight savings

### ISSUE THREAD

**Issue by laurencruz** [PrimitiveSocial/MaderaPublic#399]
Hello,

We need to update the following property office hours:

- [ ] Lake Village East: Monday-Wednesday 9a-6p, Thursday 9a-7p, Friday 9a-6p & Saturday 10a-5p
- [ ] Lake Village North: Monday 9a-7p, Tuesday-Friday 9a-6p, & Saturday 10a-5p
- [ ] Clear Fork Trail: Monday-Friday 9a-6p & Saturday 10a-5p
- [ ] Cross Creek Ranch: Monday-Friday 9a-6p & Saturday 10a-5p
- [ ] Red Rock: Monday-Friday 9a-6p & Saturday 10a-5p
- [ ] Trinity Oaks: Monday-Friday 9a-6p & Saturday 10a-5p
- [ ] Parkridge Place: Monday-Friday: 8:30 AM to 5:30 PM, Saturday 10-2

Please let me know if you have any questions.
Thank you,
Lauren

**Comment by mollybfisher** [comment]
Completed on Friday, March 22.
