### ISSUE TITLE
For properties associated we need master agreement option

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#45]
Aha! Link: https://primitivesocial.aha.io/features/MR-124

**Comment by joshmath** [comment]
@treywoodward  @jerredhurst  I have no clue what to do with this one

**Comment by treywoodward** [comment]
@joshmath this is talking about templated agreements that can be used globally for properties to give their vendors.

**Comment by mollybfisher** [comment]
closed this [on Oct 19, 2018](#event-1914966404)
