### ISSUE TITLE
Could there be a place to attach the images that make up a batch?  

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#47]

**Comment by J-Anders** [comment]
This request is talking about Check Images in a Deposit batch.  We currently list the checks that are part of a batch.  We would also like to be able to attach an image of the check.  This image will most often be obtained by the Property Manager scanning an image of the check at the office.

**Comment by jerredhurst** [comment]
Currently we have the option to upload an attachment (which would most likely be a pdf of all of the checks scanned).  Do we need to break it out and have an attachment per line item.  So, 1 file/attachment per check?

![image](https://user-images.githubusercontent.com/13042804/43867714-fbeb6e86-9b2f-11e8-96b6-f2c33b1f0395.png)

**Comment by J-Anders** [comment]
My initial reply would be yes, the ability to attach a check to an
individual line item.
