### ISSUE TITLE
If I click "Add New" then x out then repeat it keeps adding groups of circles to the completion tracker.  Clearing cache fixes the issue.

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#5]

**Comment by joshmath** [comment]
@cfjaynes Is the Resident Screening just going to be an ID Number?

**Comment by cfjaynes** [comment]
It will just be an ID number specific to the property as mentioned on page 11 of the "ResidentScreening Full XML API Gateway Implementation Guide".  The field is called propertyID.
![request object](https://user-images.githubusercontent.com/41012287/43228792-2beb9308-9028-11e8-9381-1dd7702066e0.png)
