### ISSUE TITLE
Investment information entry "REMODAL COST" is misspelled.

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#6]
<All Properties> -> New Property -> Step 1
      Investment information entry "REMODAL COST" is misspelled.

<All Properties> -> New Property -> Step 4
      On this step we would need at least one bank account each for  LLC/LP, Operating, Capital and Rehab 
             with the ability to add more as desired.  
      Somewhere else we will need the ability to add and manage bank accounts.

**Comment by joshmath** [comment]
fixed
