### ISSUE TITLE
Missing Sections

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#68]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ]       Bank account information

- [ ]       Entity information

- [x]       Bluemoon setup (this is the Bluemoon integration ID)

- [x]       Resident Screening (This is the integration ID)
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-121

**Comment by joshmath** [comment]
Need a little more direction here... @treywoodward

**Comment by treywoodward** [comment]
@joshmath Investment Properties

**Comment by treywoodward** [comment]
Resolved.
