### ISSUE TITLE
Property Overview Suggested Changes

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#7]
<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Add property detail to the overview page, showing address regional contact info, is it owned or managed and the like

- [x] We need access to Guest Cards & Applications (currently accessed through Residents)

- [x] Need action required shown on the resident list page.  This would show people who have completed an action and are waiting on property staff to take action.  Example: follow ups to GCs, processing applications and background check completion.
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-133

**Comment by joshmath** [comment]
@cfjaynes can you tell us specifically what you want to see on the property overview page?

"Need action required shown on the resident list page.  This would show people who have completed an action and are waiting on property staff to take action.  Example: follow ups to GCs, processing applications and background check completion."

The above information would show up on the task list for the appropriate staff member

**Comment by treywoodward** [comment]
@joshmath 

Add property details to the overview page (address, regional contact info, if it’s owned or managed)
Dashboard should give access to Guest Cards & Applications (currently only accessed through Residents)
Dashboard needs an “action required” section. This would show people who have completed an action and are waiting on property staff to take action. Example: follow ups to Guest Cards, processing applications, and background check completions.
