### ISSUE TITLE
 I would argue a co-resident should be mapped to a primary resident and listed somewhere inside

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#76]
<Property> -> Residents -> <A resident>.

Aha! Link: https://primitivesocial.aha.io/features/MR-120

**Comment by jerredhurst** [comment]
Is a Co-Resident a Spouse and therefore tied to a Resident or is a Co-Resident and additional Resident such as a roommate, etc?

**Comment by J-Anders** [comment]
Anyone that qualifies for the lease is considered a Resident.  All Residents (co-Residents, spouses, live-ins, whatever) are uniformly responsible for the lease.  Those occupants that are not financially responsible (children, other occupants not part of the lease) are considered Occupants.  These are typically minors.  What we need is to separate Residents from Occupants mapped to a unit, and allow a many-to-one ratio for both Residents and Occupants.

**Comment by J-Anders** [comment]
@treywoodward Trey, are we still working on this one?

**Comment by treywoodward** [comment]
@J-Anders 
We are. 
Once we wrap it up, I'll close this issue out.
