### ISSUE TITLE
Prior to month close, will there be some sort of automatic audit that can run?

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#81]
Aha! Link: https://primitivesocial.aha.io/features/MR-119

**Comment by treywoodward** [comment]
(ie before closing AP, a report generates that shows if there are invoices with different invoice dates and invoice periods or a payment in one period and the invoice in another period)

**Comment by jerredhurst** [comment]
Yes, we will need to you guys to define the rules in detail for each process.
