### ISSUE TITLE
What is the format limitations for GL Account #?

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#89]

**Comment by jerredhurst** [comment]
@cfjaynes @madera-tray Currently we do not have any.  Please provide and we can add those.

**Comment by madera-tray** [comment]
Current format in valence is ####-####.  For the initial product launch we should make this format the same as that within Valence.  Whenever the software gets marketed, we should look at adding the ability to have other common formats, e.g. ######-######, #####-#####, ####-##.

**Comment by mistycleb** [comment]
Formatting when adding a new account is not locked

**Comment by J-Anders** [comment]
Validated
