### ISSUE TITLE
Can we make a GL code restricted? How do we set the rules for this? 

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#90]
Typcially this is only for Supervisor or Admin access.

**Comment by jerredhurst** [comment]
We need to discuss in detail, but short answer is Yes

**Comment by J-Anders** [comment]
Typically, the GL codes are established when an Account is created.  Creating and editing an Account should be limited to Accounting Supervisors.  

While we're on the subject, the Accounts tab should not be part of the main General Ledger page.  There is little daily/ongoing value to this information.  Instead, Accounts should be perhaps under Settings, only accessed when adding or editing an account.

**Comment by J-Anders** [comment]
Please move Accounts under Settings.  

Also, we need to establish rules where a person can not post to a Header Account, and instead must post to a sub Account under that Header Account.  [In this spreadsheet,](https://docs.google.com/spreadsheets/d/19d5Qm_OlgwbpG2-U4fio-brnihRkHlT6cqykCLPXZXM/edit#gid=0) the Header Accounts are Bolded.  These should not be able to be posted to.

Additionally, the GL Accounts should match these accounts.

Finally, in the Setup page for setting up a new GL Code, we need an input field that lets say this newly created GL Account is a sub-account of another already created GL.

**Comment by jerredhurst** [comment]
Will they go to Settings > Accounts to lookup transactions and balances for accounts?  Most accounting systems allow you a quick way to browse accounts.
