### ISSUE TITLE
Can we identify if a GL account is a Parent, sub-group or sub-account.

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#91]
Parent and sub-groups would not be allowed to have JE’s posted to them. Only sub-accounts can have JE’s posted to them.

Aha! Link: https://primitivesocial.aha.io/features/MR-118

**Comment by mistycleb** [comment]
Cannot test functionality yet

**Comment by J-Anders** [comment]
You establish whether a GL Account is parent/child in Settings, Chart of Accounts.  However, you can not see this detail when looking at the GL Accounts Tab.  We should add the indents or "H" tag to these accounts in this view as well.

**Comment by jerredhurst** [comment]
Currently an account that "cannot be posted to" is considered a "heading" account is denoted as such.

Children are indented under their "parent"

![image](https://user-images.githubusercontent.com/13042804/44408813-c1966780-a526-11e8-9d9e-addd57cc4625.png)

Please let us know if this will not work.

**Comment by mistycleb** [comment]
We are still able to post to the heading accounts.  I just did a test entry to cash (1100-0000)
