### ISSUE TITLE
Need to be able to create and maintain departments

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#93]
Aha! Link: https://primitivesocial.aha.io/features/MR-117

**Comment by jerredhurst** [comment]
Can we discuss in more detail?

**Comment by J-Anders** [comment]
Currently, the Accounting module is all about the external accounting of properties, maintenance, investors, etc.  However, in future releases, we will look to extend the Accounting module to include internal accounting.  When this occurs, it will be important to be able to assign transactions to internal departments.  We are not looking for additional functionality within the software now, however we want to ensure that the data model accomodates this expansion easily when we get there.

**Comment by treywoodward** [comment]
Resolved.
