### ISSUE TITLE
Invoice: Need to have a place to enter a unit number and rehab category on invoices.

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#96]
Aha! Link: https://primitivesocial.aha.io/features/MAD-682

**Comment by jerredhurst** [comment]
Is this per line item or per invoice?

**Comment by MaderaMike** [comment]
Per line item

**Comment by mistycleb** [comment]
Validated functionality

Will the unit numbers be restricted to each property?  (For example, one property may have units numbered 101, 102, etc and another may be A503266, A503267.  We would only want the unit numbers in the selection to be for the property we are entering the invoice for.)

**Comment by treywoodward** [comment]
Units will be restricted by Property.
