### ISSUE TITLE
Invoice: Need to ability to void an invoice and require a reason to be entered.

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#98]
Aha! Link: https://primitivesocial.aha.io/features/MR-116

**Comment by mistycleb** [comment]
Validated  This looks great!!
This function does bring up a couple of questions:
1. When voided an invoice, I am guessing the GL codes affected will just be reversed.  Is that correct?
2.  If an invoice from a prior (closed) period is voided, will this reverse take place in the current period?
3.  Can we restrict the ability to "void" to only unpaid/open invoices?  Paid invoices would need to be handled in a different way so we can address the payment issue as well.
